name: Deploy static site to GitHub Pages

# Kích hoạt workflow khi có push lên nhánh 'main'
on:
  push:
    branches:
      - main

# Cấp quyền đọc và ghi cần thiết
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      # BƯỚC KHẮC PHỤC QUAN TRỌNG:
      # Thay đổi đường dẫn triển khai từ '.' thành 'Project1'
      # Điều này đảm bảo toàn bộ nội dung trong Project1/ (bao gồm index.html) 
      # sẽ được triển khai vào thư mục gốc của trang web (public root).
      - name: Upload artifact (from Project1 folder)
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'Project1' # Đảm bảo trỏ đúng vào thư mục chứa index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
