name: Deploy Pages from project1

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare public folder
        run: |
          set -e
          mkdir -p public
          # copy thư mục code ra artifact
          cp -r project1 public/
          cp -r styles public/
          # copy thư mục chứa ảnh (dùng 'images' hoặc 'image')
          cp -r images public/ 2>/dev/null || true
          cp -r image  public/ 2>/dev/null || true

          # tạo index.html ở root để redirect sang project1/index.html
          cat > public/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>Redirecting…</title>
          <meta http-equiv="refresh" content="0; url=project1/index.html">
          <link rel="canonical" href="project1/index.html">
          HTML

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

